### ISSUE TITLE
Apply a named style to an Element

### ISSUE THREAD

**Issue by oncletom** [connium/simple-odf#48]
**Is your feature request related to a problem? Please describe.**

I am trying to generate something like this:

```xml
<text:list text:style-name="List_20_1">
<text:list-item>
  <text:p text:style-name="ListeAPuce">Item 1</text:p>
</text:list-item>
<text:list-item>
  <text:p text:style-name="ListeAPuce">Item 2</text:p>
</text:list-item>
</text:list>
```

My code looks like this:

```js
const list = document.addList();

items.forEach((item) => {
  list.addItem(item.getText());
});
```

However, the style name seems to be automatically generated and I can't find a way to apply my own name.

**Describe the solution you'd like**

Ideally, I'd like to do something like

```js
const list = document.addList().setAttribute('text:style-name', 'List_20_1');

items.forEach((item) => {
  list.addItem(item.getText()).setAttribute('text:style-name', 'ListeAPuce')
});
```

Or with styles

```js
const {ListStyle, ParagraphStyle} = require("simple-odf");
const List_20_1 = new ListStyle().setName('List_20_1');
const ListeAPuce = new ParagraphStyle().setName('ListeAPuce');

const list = document.addList().setStyle(List_20_1);

items.forEach((item) => {
  list.addItem(item.getText()).setStyle(ListeAPuce);
});
```

**Describe alternatives you've considered**

I have considered apply a `ParagraphStyle` or `ListStyle` but I can't name it explicitely.

Thanks for your help :-)

**Comment by connium** [comment]
Thanks for your submission and for providing that much detail! :sparkles: 

You are right, the style names are automatically generated. Actually it's the hash code of the style properties. This is done to in order to identify equal styles.

Right now with simple-odf you can create a paragraph style and apply it to multiple paragraphs.

```javascript
const myParagraphStyle = new ParagraphStyle();
// configure the style as you want

document.addParagraph().setStyle(myParagraphStyle);
document.addParagraph().setStyle(myParagraphStyle);
```

Unfortunately there is no `ListStyle` yet. I plan to add this in a future version.

You write, that you want to name the styles. What is your intention for this? Do you want to edit the resulting file in an editor like [LibreOffice](https://libreoffice.org/) with the styles being displayed in the styles dropdown? Do you want to specify default styles for the different elements (like paragraph, headline, list, ...) which will be used by default unless a different style is set directly to the element?

Please give me a hint because that will help me to identify which kind of style is required (internally there are two styles: think of pre-defined and just-in-time).

**Comment by oncletom** [comment]
The use case is generating a document for which I have external styles. When these style names are applied to elements, they inherit their visual properties (page breaks, font size, colour, etc.)

It affects any kind of element: headline, paragraph, spans, etc.

**Comment by connium** [comment]
If you apply a style name to an element without defining the style itself in the document, the document is invalid. :boom: 

If I get it right, you have defined global styles in your editor and the editor might use them to render the document as you expect it (not quite sure about this). As I said the document in this case is invalid and if you send it to someone else the other person won't see the same output as you do (because the editor cannot find any styles).

I don't think you will get what you expect if I provide a way to define styles with custom name, because in that case the named style will be included in the document and will be used by your editor instead of your equal named editor styles. So the only way to achieve what you want is, to offer a way to set style names without defining the according styles...

I'll definitely add predefined default styles in the upcoming version (already working on it). It then will be easy to add the possibility to define custom document wide styles as well. :writing_hand: 
To be honest, I don't want to offer a way for creating invalid ODF files because I think this will cause some error reports about not-working documents. If you just want to apply style names I think the best way is to create the document (without applying any styles), save it to XML and run a find/replace operation on the XML replacing e.g. `text:p` with `text:p text:style-name="yourStyleName"`.

What do you think? If I misunderstood your scenario, please help me to get it right :sweat_smile:

**Comment by oncletom** [comment]
> If you apply a style name to an element without defining the style itself in the document, the document is invalid.

Yes you are totally right, and I did not mention I included the styles in the document too—I had to generate the XML document on my own with xmldom and to inject the relevant style tags alongside the document body (generated by simple-odf).

I guess then it's not about definining solely the stylename but to provide a hook or something to add (style/master-styles) XML tags at a `toXml()` method level. [Here are all the elements](https://github.com/oncletom/nodebook/blob/master/src/asciidoctor-opendocument-styles.js) I end up adding to a bare ODT file.

**Comment by connium** [comment]
I'm sorry this library cannot help you right now.

As I said before, there will be default styles and named styles in the future but I cannot promise it will work for you. It looks like you use several styling features that are not available in this project. Maybe they will one day.

I'll keep your request in mind when developing new features for this library. The hook-things sounds like a good a idea to me.

Thanks for giving me insights into your needs.
