### ISSUE TITLE
Setting a style with PageBreak on a Header removes its level

### ISSUE THREAD

**Issue by leonheess** [connium/simple-odf#749]
First of all: Thank you so much for this amazing package!

However, I'm having trouble putting my header on a new page while keeping its level properties. 

```
body.addHeading('Hi', 2).setStyle(new ParagraphStyle().setPageBreak(PageBreak.Before))
```

Expected: 

\*new page starts\*
## Hi

------------

Actual:

\*new page starts\*

Hi

**Comment by connium** [comment]
Thanks for your kind words!

That's an interesting behavior you've discovered there. Thank you for reporting it!

I guess you open the file you created with simple-odf in an office suite like LibreOffice or OpenOffice, right? Well, there's a little magic happening in the background (I'm not entirely sure I like it).

Let's assume you create a very basic document with simple-odf like this:

```ts
const document = new TextDocument();
const body = document.getBody();
body.addHeading('Title');
body.addParagraph('Hello world');
await document.saveFlat('./test.fodt');
```

If you open this file with LibreOffice you will see something like this:

> ## Title
> Hello world

But where does this come from? simple-odf doesn't add any default styles and in the example above we haven't define any either. What we see here is the default styling which the office suite applies if no styles are defined. In order to see what the office suite applies, save the document from within the office suite. You will notice that the file size has increased by magnitudes. If we open this file with a simple text editor and we will see a whole bunch of styles that were added by the office suite.

I don't think there is any way for simple-odf to preserve styles that are applied by an office suite **after** the document has been generated.
This means that you'll have to define the style for the heading on your own:

```ts
const document = new TextDocument();
const body = document.getBody();
const headingStyle = new ParagraphStyle();
headingStyle.setFontSize(16)
    .setTypeface(Typeface.Bold)
    .setMargin(0, 0, 40, 20)
    .setKeepWithNext()
    .setPageBreak(PageBreak.Before);
body.addHeading('Title').setStyle(headingStyle);
body.addParagraph('Hello world');
await document.saveFlat('./test.fodt');
```

I hope I could help you.

**Comment by connium** [comment]
As this isn't anything simple-odf can fix (except by providing it's own default styles), I'll close this issue.
If you feel that this is something we should address, feel free to reopen the issue with some detailed explanation what your expectations are and how simple-odf should deal with it in detail. Of course you can also open a PR 😉
